project_name: bookhunter

before:
  hooks:
    - go mod tidy

builds:
  - id: bookhunter
    ldflags:
      - -s -w
      - -X github.com/bibliolater/bookhunter/cmd.gitMajor={{ .Major }}
      - -X github.com/bibliolater/bookhunter/cmd.gitMinor={{ .Minor }}
      - -X github.com/bibliolater/bookhunter/cmd.gitVersion={{ .Version }}
      - -X github.com/bibliolater/bookhunter/cmd.gitCommit={{ .Commit }}
      - -X github.com/bibliolater/bookhunter/cmd.gitTreeState=clean
      - -X github.com/bibliolater/bookhunter/cmd.buildDate={{ .Date }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - "386"
      - amd64
      - arm64

scoop:
  bucket:
    owner: bibliolater
    name: scoop-bucket
    branch: master
  commit_author:
    name: syhily
    email: syhily@gmail.com
  homepage: "https://github.com/bibliolater"
  description: "Software to download chinese ebooks from Internet."
  license: MIT

brews:
  - name: bookhunter
    tap:
      owner: bibliolater
      name: homebrew-tap
      branch: master
    commit_author:
      name: syhily
      email: syhily@gmail.com
    folder: Formula
    homepage: "https://github.com/bibliolater"
    description: "Software to download chinese ebooks from Internet."
    license: "MIT"
    install: |
      bin.install "bookhunter"

      # Install shell completions
      output = Utils.safe_popen_read("#{bin}/bookhunter", "completion", "bash")
      (bash_completion/"bookhunter").write output

      output = Utils.safe_popen_read("#{bin}/bookhunter", "completion", "zsh")
      (zsh_completion/"_bookhunter").write output

      output = Utils.safe_popen_read("#{bin}/bookhunter", "completion", "fish")
      (fish_completion/"bookhunter.fish").write output
    test: |
      system "#{bin}/bookhunter -v"

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^web:'

archives:
  - id: bookhunter
    builds:
      - bookhunter
    format: tar.gz
    wrap_in_directory: "true"
    format_overrides:
      - goos: windows
        format: zip

snapshot:
  name_template: "{{ incminor .Version }}-next"
